image: maven:3.8-jdk-11

services:
  - docker:dind

stages:
  - build
  - deploy
  - test

build-jar-file:
  stage: build
  script:
    - mvn clean install 
    - mvn package
 
  artifacts:
        paths:
            -  target/*.jar

build-docker-image-&push:
  services:
    - docker:dind
  image: docker:dind
  stage: build
  dependencies: 
    - build-jar-file
    
  script:
    
    - docker build -t spring-boot-backend:v1 .  
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
    - docker tag spring-boot-backend:v1 hakpovi/spring-boot-backend:v1 
    - docker push hakpovi/spring-boot-backend:v1   

run-docker-container:
  stage: test
  services:
    - docker:dind
  image: ubuntu
  dependencies:
    - build-docker-image-&push
  script:
    - apt-get install curl -y
    - docker run  -d hakpovi/spring-boot-backend:v1
    - curl -vvv http://localhost:8090 > curl-result.txt
    - cat curl-result.txt
    
  #only:
   # - master
  #only: [] 




